---
title: "otemma_env"
format: pdf
editor: visual
execute:
  echo: true
editor_options: 
  chunk_output_type: console
---

```{r}
#| echo: false
#| output: false
library(dplyr)
library(purrr)
library(tidyr)
library(ggplot2)
library(readxl)
library(stringr)
library(corrplot)
library(vegan)
library(labdsv)
library(cluster)
library(gclus)
```

```{r}

# Load datasets
load(file='otemma.Rdata')

```

## Environmental data (geospatial and labo)

```{r}

# Clean unwanted variables and NAs
env <- cbind(otemma_geo, otemma_labo) # combine geospatial and labo variables
env <- env %>% select(-nitrogen) # remove nitrogen because always 0
env <- env %>% select(-orient_deg) # remove orientation because too many NAs
env <- env[complete.cases(env),] # remove sites with NAs
row_ids <- as.numeric(rownames(env)) # sites kept after processing

# Box plots
env %>% 
  gather() %>% 
  ggplot(aes(y = value)) +
  geom_boxplot(position = position_dodge(0.8)) +
  geom_boxplot() +
  # xlab("Variable") +
  # ylab("Value") +
  ggtitle("Environmental variables") +
  facet_wrap(~key, scales = "free_y", ncol = 4)

# Correlation, before selecting variables
env.cor <- cor(env)
col<-colorRampPalette(c("white","yellow","red","blue"))
corrplot(env.cor, method="color",col=col(100),diag=FALSE, main='Correlation (before)')

# Selecting only meaningfull variables (based on correlation)
env_vars <- c(
  'altitude',
  'x',
#  'y',
  'slope',
  'dist_main_river',
  'dist_close_river',
  'carbon',
  'hydrogen',
  'mass_block',
  'mass_coarse',
  'mass_medium',
#  'mass_fine',
  'granulo_sand'
#  'granulo_silt',
#  'granulo_clay'
)
env <- env[,env_vars]

# Correlation, after selecting variables
env.cor <- cor(env)
corrplot(env.cor, method="color",col=col(100),diag=FALSE, main='Correlation (after)')

```

## Vegetation data

```{r}

# Eliminate rows that were removed in the 'env' dataset
veg <- otemma_species[row_ids,]

# Eliminate rows with no vegetation observed
veg <- veg[-4,]
env <- env[-4,]

# Possible transformations
veg_code.orig <-    c('r',   '+',  '1',  '2a', '2b',  '3',   '4',    '5')
veg_code.meancov <- c( 0.05,  0.5,  3,    10,   20,    37.5,  62.5,   87.5)
veg_code.numdom <-  c( 0.1,   0.5,  1,    2,    2.5,   3,     4,      5)

# Transformation to mean coverage
veg <- abundtrans(veg, veg_code.orig, veg_code.meancov)
veg[is.na(veg)] <- 0 # replace NAs by 0

# Hellinger transformation
veg.hel <- decostand(veg, 'hell')

# Remove species not present
veg.hel <- veg.hel %>% select(where(~ any(. != 0)))

```

### Clustering

```{r}

# Euclidian distance
veg.dist <- vegdist(veg.hel, method='euc')
col<-colorRampPalette(c("white","yellow","red","blue"))
corrplot(as.matrix(veg.dist), method="color", col=col(100), is.corr=FALSE)

# Dendogram
veg.dendro <- hclust(veg.dist, method='ward.D2')
plot(veg.dendro, hang=-1)

# Clusters
n_clust <- 3
veg.group <- cutree(veg.dendro, k=n_clust)
veg.sil <- silhouette(veg.group, veg.dist)
rownames(veg.sil) <- row.names(veg.group)
plot(veg.sil, cex.names=0.8, col=2:(n_clust+1))

# Dendogram with clusters
veg.dendro_clust <- reorder.hclust(veg.dendro, veg.dist)
plot(veg.dendro_clust, hang=-1, sub='')
rect.hclust(veg.dendro_clust, border=2:4, k=n_clust)

# Characteristic species
veg.iva <- indval(veg.hel, veg.group)
veg.freq <- apply(veg.hel>0, 2, sum)
veg.iva$maxcls
veg.iva$indcls
veg.iva$pval
veg.freq

veg.iva_tab <- data.frame(
  c('max.gr', veg.iva$maxcls),
  c('ind.gr', veg.iva$indcls),
  c('pval', veg.iva$pval),
  c('freq', veg.freq)
)
names(veg.iva_tab) <- veg.iva_tab[1,]
veg.iva_tab <- veg.iva_tab[-1,]

```

### Constrained ordination (RDA)

```{r}

# RDA
veg.rda <- rda(veg.hel~., env)
summary(veg.rda)

# RDA plot with clusters
k <- length(levels(factor(veg.group)))
plot(veg.rda, display='sites', type='none', scaling=1, choices=c(1,2), main = "Triplot RDA veg.hel ~ env")
points(veg.rda, cex=1.5, col=1+c(1:k)[veg.group], pch=14+c(1:k)[veg.group], choices=c(1, 2), scaling=1)
text(veg.rda, "sites", pos=4, cex=1.2, choices=c(1, 2), scaling=1)
text(veg.rda, "species", cex=0.8, col="red", choices=c(1, 2), scaling=1)
text(veg.rda, "bp", cex=0.8, col="blue", choices=c(1, 2), scaling=1)

# Quality measures
veg.rda.r2 <- RsquareAdj(veg.rda)$r.squared # r squared
veg.rda.r2adj <- RsquareAdj(veg.rda)$adj.r.squared

screeplot(veg.rda, col="bisque") # variance explained by axis

anova(veg.rda, by = "axis", permutations = how(nperm = 999)) # permutation test

vif.cca(veg.rda) # vif test


```

